wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1680558194.681194
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 1
      - 16
      - 23
      4: 3.10.9
      5: 0.14.0
      8:
      - 5
architecture:
  desc: null
  value: GIN
data_dir:
  desc: null
  value: data/test.pkl.gz
dimensions:
  desc: null
  value: 3
epochs:
  desc: null
  value: 1000
layers:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
