wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1681400191.5626
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.9
      5: 0.14.0
      8:
      - 5
architecture:
  desc: null
  value: GIN-2D
data_dir:
  desc: null
  value: null
dimensions:
  desc: null
  value: null
epochs:
  desc: null
  value: 500
layers:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.001
